### ISSUE TITLE
TypeError after upgrading from 0.43.8

### ISSUE THREAD

**Issue by pposca** [slidevjs/slidev#1176]
**Describe the bug**
I was never able to upgrade successfully from v0.43.8 to v0.43.9 due an error similar to #1167. Now that v0.43.13 is suppose to solve #1167, I am getting a TypeError, that seems to come from vite-plugin-remote-assets:

```
file:///home/pposca/proyectos/clases/daw-dwec/node_modules/.pnpm/@slidev+cli@0.43.13_@types+markdown-it@13.0.5_playwright-chromium@1.39.0_postcss@8.4.31/node_modules/@slidev/cli/dist/chunk-G52N36S6.mjs:1652
    config.remoteAssets === true || config.remoteAssets === mode ? import("vite-plugin-remote-assets").then((r) => r.default({
                                                                                                                            ^

TypeError: r.default is not a function
    at file:///home/pposca/proyectos/clases/daw-dwec/node_modules/.pnpm/@slidev+cli@0.43.13_@types+markdown-it@13.0.5_playwright-chromium@1.39.0_postcss@8.4.31/node_modules/@slidev/cli/dist/chunk-G52N36S6.mjs:1652:125
    at async Promise.all (index 6)
    at async ViteSlidevPlugin (file:///home/pposca/proyectos/clases/daw-dwec/node_modules/.pnpm/@slidev+cli@0.43.13_@types+markdown-it@13.0.5_playwright-chromium@1.39.0_postcss@8.4.31/node_modules/@slidev/cli/dist/chunk-G52N36S6.mjs:1700:11)
    at async createServer (file:///home/pposca/proyectos/clases/daw-dwec/node_modules/.pnpm/@slidev+cli@0.43.13_@types+markdown-it@13.0.5_playwright-chromium@1.39.0_postcss@8.4.31/node_modules/@slidev/cli/dist/chunk-QHSQGFN7.mjs:2509:11)
    at async initServer (file:///home/pposca/proyectos/clases/daw-dwec/node_modules/.pnpm/@slidev+cli@0.43.13_@types+markdown-it@13.0.5_playwright-chromium@1.39.0_postcss@8.4.31/node_modules/@slidev/cli/dist/cli.mjs:120:16)
```

This error looks like [this one](https://github.com/antfu/vite-plugin-remote-assets/issues/6) reported in vite-plugin-remote-assets repo.

**To Reproduce**
Just trying to upgrade from v0.43.8...

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Any
 - Slidev version: 0.43.13

**Comment by vmoranv** [comment]
Describe the bug
√ Entry file "slides.md" does not exist, do you want to create it? ... yes
ReferenceError: __dirname is not defined
    at Object.handler (file:///C:/Users/vmora/AppData/Roaming/npm/node_modules/@slidev/cli/dist/cli.mjs:108:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

To Reproduce
Just trying to upgrade from v0.43.8...

Desktop (please complete the following information):

OS: Windows 11
Browser: Any
Slidev version: 0.43.13
