### ISSUE TITLE
Unable to run dev server or build due to missing windi.config.js

### ISSUE THREAD

**Issue by HamzaMoiyadi** [slidevjs/slidev#241]
**Describe the bug**
After upgrading to v0.20.1, I am unable to build or serve the slides due to `(node:14620) UnhandledPromiseRejectionWarning: Error: Cannot find module 'windi.config.js'`

**To Reproduce**
1. Upgraded an existing slidev project to v0.20.1
2. Run `yarn dev` or `yarn build`
4. See the error in the termincal

**Desktop (please complete the following information):**
 - OS: Kubuntu 20
 - Slidev version: 0.20.1

**Comment by antfu** [comment]
Can you share repro? Thanks

**Comment by HamzaMoiyadi** [comment]
@antfu I've given you access to my repository. Will that suffice?

**Comment by antfu** [comment]
Fixed in v0.20.4. However, it's better to use windicss setup hook whenever possible to have better integrations (newly introduced in v0.14): https://sli.dev/custom/config-windicss.html
